# -*- coding: utf-8 -*-
"""cicloGiorni

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P44KBU0aja1ihq4jOWlOxm8pn5SApll2

# Il calendario mediocre
  Scrivi un programma che dato:<br>
    - Il numero di giorni nel mese<br>
    - Il giorno della settimana in cui questo comincia:<br> (0: lunedì ... 6: domenica)<br>
  Stampi il calendario di un mese.

  Esempio:
  ```
    Input: numero giorni = 31, giorno settimana = 0
    Output: Lun 1
            Mar 2
            Mer 3
            Gio 4
            Ven 5
            Sab 6
            Dom 7
            Lun 8
            Mar 9
            Mer 10
            Gio 11
            Ven 12
            Sab 13
            Dom 14
            Lun 15
            Mar 16
            Mer 17
            Gio 18
            Ven 19
            Sab 20
            Dom 21
            Lun 22
            Mar 23
            Mer 24
            Gio 25
            Ven 26
            Sab 27
            Dom 28
            Lun 29
            Mar 30
            Mer 31
```
"""

giorni=["lunedì", "martedì", "mercoledì", "giovedì", "venerdì", "sabato", "domenica"]

numeroGiorni=int(input("Inserire il numero di giorni del mese: "))
while (True):
  if(numeroGiorni < 28 or numeroGiorni > 31):
    numeroGiorni=int(input("Valore non accettabile. Reinserire il numero di giorni del mese: "))
  else:
    break

giornoSett=int(input("Inserire il giorno della settimana(0 per lunedì... e 6 per domenica): "))
while (True):
  if(giornoSett < 0 or giornoSett > 6):
    giornoSett=int(input("Valore non accettabile. Reinserire il giorno della settimana(0 per lunedì... e 6 per domenica): "))
  else:
    break

giornoCorrente = giornoSett

for i in range(numeroGiorni):
  if giornoCorrente % 7 == 0:
    giornoCorrente = 0
  print(f"{giorni[giornoCorrente]} {i+1}")
  giornoCorrente = giornoCorrente + 1

print("Hatsune Miku is the key!")