# -*- coding: utf-8 -*-
"""EserciziArray1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mf50CnmPqDdeBHLEccMT-5VdXFIqeLaA

[For in python](https://www.w3schools.com/python/python_for_loops.asp) -
[Array in python](https://www.w3schools.com/python/python_arrays.asp)

**n.b. Per ogni esercizio scrivere una versione con il WHILE e una con il FOR**

**Esercizio 1**
```
Costruire tramite un ciclo for un vettore di N posizioni, inserendo in ogni elemento il valore del suo indice.
"""

vet = []

numVet=int(input("Inserire il numero di posizioni del vettore: "))
while (True):
  if numVet <= 0:
    numVet=int(input("Valore non accettabile. Reinserire il numero di posizioni del vettore: "))
  else:
    break

for i in range(numVet):
  vet.append(i)
  print(i)

"""**Esercizio 2**
```

Dato un vettore di N elementi sommare gli elementi di indice pari e dispari, quindi visualizzare la somma dei numeri pari e la somma dei numeri dispari

"""

sommaPari = 0
sommaDispari = 0
vet = []

numVet=int(input("Inserire il numero di posizioni del vettore: "))
while (True):
  if numVet <= 0:
    numVet=int(input("Valore non accettabile. Reinserire il numero di posizioni del vettore: "))
  else:
    break

for i in range(numVet):
  vet.append(int(input("Inserire il valore dell'elemento: ")))
  if(i % 2 == 0):
    sommaPari = sommaPari + vet[i]
  else:
    sommaDispari = sommaDispari + vet[i]

print("La somma dei numeri pari è: ", sommaPari)
print("La somma dei numeri dispari è: ", sommaDispari)

"""**Esercizio 3**
```

Costruisci un vettore di N elementi inserendo almeno due 0. Dopo aver creato il vettore scorrilo e ad ogni 0 incontrato stampa la somma di tutti gli elementi precedenti allo 0 e il loro numero.

"""

vet = []

numVet=int(input("Inserire il numero di posizioni del vettore: "))
while (True):
  if numVet <= 0:
    numVet=int(input("Valore non accettabile. Reinserire il numero di posizioni del vettore: "))
  else:
    break

for i in range(numVet):
  vet.append(int(input("Inserire il valore dell'elemento: ")))

for i in range(numVet):
  if(vet[i] == 0):
    somma = 0
    for j in range(i):
      somma = somma + vet[j]
    print("La somma dei numeri precedenti a 0 è: ", somma)

"""**Esercizio 4**
```
Dato un vettore numerico di N posizioni determinare la somma e la media *delle* componenti positive e quella delle componenti negative.
```

"""

vet = []
sommaPos = 0
sommaNeg = 0
mediaPos = 0
mediaNeg = 0
numPos = 0
numNeg = 0

numVet=int(input("Inserire il numero di posizioni del vettore: "))
while (True):
  if numVet <= 0:
    numVet=int(input("Valore non accettabile. Reinserire il numero di posizioni del vettore: "))
  else:
    break

for i in range(numVet):
  vet.append(int(input("Inserire il valore dell'elemento: ")))
  if(vet[i] > 0):
    sommaPos = sommaPos + vet[i]
    numPos = numPos + 1
  elif(vet[i] < 0):
    sommaNeg = sommaNeg + vet[i]
    numNeg  =  numNeg + 1

mediaPos = sommaPos / numPos
mediaNeg = sommaNeg / numNeg

print("La somma dei numeri positivi è: ", sommaPos)
print("La media dei numeri positivi è: ", mediaPos)

print("La somma dei numeri negativi è: ", sommaNeg)
print("La media dei numeri negativi è: ", mediaNeg)

"""**Esercizio 5**
```
Scrivere un programma che dopo aver letto  gli elementi di un vettore contenente almeno due 0 assegni a un secondo vettore gli elementi del primo disposto nello stesso ordine tranne gli elementi di valore zero che vengono posti tutti in fondo. Visualizzare il vettore così ottenuto.```

"""

vet = []
vet2 = []
zeriPresenti = 0

numVet=int(input("Inserire il numero di posizioni del vettore: "))
while (True):
  if numVet <= 0:
    numVet=int(input("Valore non accettabile. Reinserire il numero di posizioni del vettore: "))
  else:
    break

for i in range(numVet):
  vet.append(int(input("Inserire il valore dell'elemento: ")))
  if(vet[i] == 0):
    zeriPresenti = zeriPresenti + 1
  else:
    vet2.append(vet[i])

for i in range(zeriPresenti):
  vet2.append(0)

print(vet2)